export const ADD_NEW_STUDENT = "students/ADD_NEW_STUDENT";
export const GET_STUDENTS = "students/GET_STUDENTS";
export const LOADING_STUDENTS = "students/LOADING_STUDENTS";
export const GET_STUDENT_TO_UPDATE = "students/GET_STUDENT_TO_UPDATE";
export const SET_STUDENTS_ACTION_SUCCEED = "students/SET_STUDENTS_ACTION_SUCCEED";
export const SET_STUDENTS_ACTION_FAILED = "students/SET_STUDENTS_ACTION_FAILED";
